/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proctor_diary;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Nilansh Thakur
 */
public class proctor_profileview extends javax.swing.JFrame {

    /**
     * Creates new form proctor
     */
    public proctor_profileview() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        showdate();
        showtime();
    }
    public void showdate(){
        java.util.Date d=new java.util.Date();
        SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy");
        datevar.setText(s.format(d));
    }
    public void showtime(){
        new Timer(0,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                java.util.Date d=new java.util.Date();
                SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss a");
                timevar.setText(s.format(d));
            }
        }).start();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proctorid = new javax.swing.JLabel();
        profileview = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        t02 = new javax.swing.JTable();
        pid = new javax.swing.JLabel();
        txt_filename = new javax.swing.JLabel();
        eduqual = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        raddress = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        datevar = new javax.swing.JLabel();
        timevar = new javax.swing.JLabel();
<<<<<<< HEAD

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        setSize(new java.awt.Dimension(900, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        proctorid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        proctorid.setForeground(new java.awt.Color(0, 153, 0));
        proctorid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proctorid.setText("PROCTOR ID:");
        getContentPane().add(proctorid, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 130, 40));

        profileview.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        profileview.setForeground(new java.awt.Color(0, 153, 153));
        profileview.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(profileview, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 11, 509, 72));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("EDUCATIONAL QUALIFICATIONS:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 300, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 102, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DATE OF BIRTH:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 300, 100));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("RESIDENTIAL ADDRESS:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, 230, 70));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 51));
        jLabel5.setText("STUDENT'S LIST :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 720, 164, 50));

        Back.setBackground(new java.awt.Color(0, 0, 0));
        Back.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Back.setForeground(new java.awt.Color(0, 153, 153));
=======
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1500, 1500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        proctorid.setBackground(new java.awt.Color(0, 0, 0));
        proctorid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        proctorid.setForeground(new java.awt.Color(255, 255, 255));
        proctorid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proctorid.setText("PROCTOR ID:");
        getContentPane().add(proctorid, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 190, 40));

        profileview.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        profileview.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(profileview, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 650, 72));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EDUCATIONAL QUALIFICATIONS:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 410, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DATE OF BIRTH:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 300, 100));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RESIDENTIAL ADDRESS:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 300, 70));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PHONE NUMBER:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 710, 220, 50));

        Back.setBackground(new java.awt.Color(0, 0, 0));
        Back.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
>>>>>>> Proctor Version 3.0 deployed on cPanel
        Back.setText("Back");
        Back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 900, 91, 41));

=======
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 830, 110, 60));

        t02.setBackground(new java.awt.Color(0, 0, 0));
        t02.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        t02.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        t02.setForeground(new java.awt.Color(255, 255, 255));
>>>>>>> Proctor Version 3.0 deployed on cPanel
        t02.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(t02);

<<<<<<< HEAD
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 730, 540, 209));

        pid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pid.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 380, 40));

        txt_filename.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_filename.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txt_filename, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 771, -1, -1));

        eduqual.setBackground(new java.awt.Color(0, 0, 0));
        eduqual.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        eduqual.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(eduqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 350, 130));

        dob.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dob.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 330, 40));

        raddress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        raddress.setForeground(new java.awt.Color(51, 153, 0));
        getContentPane().add(raddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, 360, 140));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("Date:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 30, -1, 80));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Time:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 130, -1, 80));

        datevar.setBackground(new java.awt.Color(0, 0, 0));
        datevar.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        datevar.setForeground(new java.awt.Color(0, 153, 153));
        datevar.setText("Date:");
        getContentPane().add(datevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 40, 260, 60));

        timevar.setBackground(new java.awt.Color(0, 0, 0));
        timevar.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        timevar.setForeground(new java.awt.Color(0, 153, 153));
        timevar.setText("Time:");
        getContentPane().add(timevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 140, 270, 60));
=======
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 710, 540, 90));

        pid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pid.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 380, 40));

        txt_filename.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_filename.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txt_filename, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 780, -1, -1));

        eduqual.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        eduqual.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(eduqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 350, 130));

        dob.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        dob.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 330, 40));

        raddress.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        raddress.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(raddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 360, 140));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("Date:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 10, -1, 80));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Time:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 110, -1, 80));

        datevar.setBackground(new java.awt.Color(0, 0, 0));
        datevar.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        datevar.setForeground(new java.awt.Color(0, 153, 153));
        datevar.setText("Date:");
        getContentPane().add(datevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 20, 260, 60));

        timevar.setBackground(new java.awt.Color(0, 0, 0));
        timevar.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        timevar.setForeground(new java.awt.Color(0, 153, 153));
        timevar.setText("Time:");
        getContentPane().add(timevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 120, 270, 60));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (845).png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 480, 390));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmslogo111.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 210, 400, 400));

        t2.setBackground(new java.awt.Color(0, 0, 0));
        t2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        t2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(t2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 710, -1, 90));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STUDENT'S LIST :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 700, 220, 50));
>>>>>>> Proctor Version 3.0 deployed on cPanel

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        /*String image3=txt_filename1.getText();
        Proctor_Page obj1=new Proctor_Page();
        ImageIcon icon=new ImageIcon(image3);
        obj1.photo1.setIcon(icon);
        //obj1.photo1.*/
        try{
       /* Class.forName("com.mysql.jdbc.Driver");
<<<<<<< HEAD
      Connection con = DriverManager.getConnection("jdbc:mysql://bykqcbjckqhrun54vgmr-mysql.services.clever-cloud.com:3306/bykqcbjckqhrun54vgmr","uu799vkgk1pcx35b","Hqy3pqsIAdaAt6gMuPNe");
=======
      Connection con = DriverManager.getConnection("jdbc:mysql://107.180.95.144:3306/isedevbm_proctor_management","isedevbm_nia","Hatake@456");
>>>>>>> Proctor Version 3.0 deployed on cPanel
        String id1=pid.getText();
        String query5=" select image from proctor where proctor_id=(?)";
        PreparedStatement st5 =con.prepareStatement(query5);
        st5.setString(1,id1);
        ResultSet rs5=st5.executeQuery();
        rs5.next();
        String image4=rs5.getString("image");
        Proctor_Page obj=new Proctor_Page();
        ImageIcon icon=new ImageIcon(image4);
        Image image=icon.getImage().getScaledInstance(obj.photo1.getWidth(),obj.photo1.getHeight(), Image.SCALE_SMOOTH);
        obj.photo1.setIcon(icon);*/
        this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proctor_profileview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proctor_profileview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proctor_profileview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proctor_profileview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proctor_profileview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel datevar;
    public javax.swing.JLabel dob;
    public javax.swing.JLabel eduqual;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
<<<<<<< HEAD
=======
    private javax.swing.JLabel jLabel16;
>>>>>>> Proctor Version 3.0 deployed on cPanel
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
<<<<<<< HEAD
=======
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
>>>>>>> Proctor Version 3.0 deployed on cPanel
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel pid;
    private javax.swing.JLabel proctorid;
    public javax.swing.JLabel profileview;
    public javax.swing.JLabel raddress;
    public javax.swing.JTable t02;
<<<<<<< HEAD
=======
    public javax.swing.JTable t2;
>>>>>>> Proctor Version 3.0 deployed on cPanel
    private javax.swing.JLabel timevar;
    public javax.swing.JLabel txt_filename;
    // End of variables declaration//GEN-END:variables
}
